# Dependabot configuration for ResumeSync Pro
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ============================================
  # Go Dependencies - API Service
  # ============================================
  - package-ecosystem: "gomod"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "go"
      - "api"
      - "security"
    commit-message:
      prefix: "feat(api)"
      prefix-development: "chore(api)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "golang.org/x/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/gin-gonic/gin"
        update-types: ["version-update:semver-major"]
    groups:
      go-security:
        patterns:
          - "golang.org/x/crypto"
          - "golang.org/x/net"
          - "golang.org/x/text"
          - "golang.org/x/sys"
        update-types:
          - "security-update"
          - "patch"
      go-testing:
        patterns:
          - "*testify*"
          - "*gomega*"
          - "*ginkgo*"
          - "*mock*"
        update-types:
          - "minor"
          - "patch"
      go-database:
        patterns:
          - "*gorm*"
          - "*postgres*"
          - "*redis*"
        update-types:
          - "patch"

  # ============================================
  # Go Dependencies - Worker Service
  # ============================================
  - package-ecosystem: "gomod"
    directory: "/apps/worker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "go"
      - "worker"
      - "security"
    commit-message:
      prefix: "feat(worker)"
      prefix-development: "chore(worker)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "golang.org/x/*"
        update-types: ["version-update:semver-major"]
    groups:
      worker-security:
        patterns:
          - "golang.org/x/crypto"
          - "golang.org/x/net"
          - "golang.org/x/text"
          - "golang.org/x/sys"
        update-types:
          - "security-update"
          - "patch"
      worker-queue:
        patterns:
          - "*redis*"
          - "*queue*"
          - "*job*"
        update-types:
          - "patch"

  # ============================================
  # Node.js Dependencies - Web Application
  # ============================================
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "javascript"
      - "web"
      - "security"
    commit-message:
      prefix: "feat(web)"
      prefix-development: "chore(web)"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for framework dependencies
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      # Ignore specific packages that break frequently
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    groups:
      react-ecosystem:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      nextjs-ecosystem:
        patterns:
          - "next"
          - "next-*"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
      testing-libraries:
        patterns:
          - "*testing*"
          - "@testing-library/*"
          - "jest*"
          - "vitest*"
        update-types:
          - "minor"
          - "patch"
      linting-formatting:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "@prettier/*"
        update-types:
          - "patch"
      ui-components:
        patterns:
          - "@headlessui/*"
          - "@heroicons/*"
          - "tailwindcss*"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"

  # ============================================
  # Docker Dependencies
  # ============================================
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "docker"
      - "api"
      - "infrastructure"
    commit-message:
      prefix: "feat(docker)"
      prefix-development: "chore(docker)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    ignore:
      # Pin specific base image versions for stability
      - dependency-name: "golang"
        update-types: ["version-update:semver-major"]
      - dependency-name: "alpine"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/apps/worker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:15"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "docker"
      - "worker"
      - "infrastructure"
    commit-message:
      prefix: "feat(docker)"
      prefix-development: "chore(docker)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "golang"
        update-types: ["version-update:semver-major"]
      - dependency-name: "alpine"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "docker"
      - "web"
      - "infrastructure"
    commit-message:
      prefix: "feat(docker)"
      prefix-development: "chore(docker)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "alpine"
        update-types: ["version-update:semver-major"]

  # ============================================
  # GitHub Actions Dependencies
  # ============================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
      - "infrastructure"
    commit-message:
      prefix: "feat(ci)"
      prefix-development: "chore(ci)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    groups:
      actions-core:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
      docker-actions:
        patterns:
          - "docker/*"
        update-types:
          - "minor"
          - "patch"
      security-actions:
        patterns:
          - "github/codeql-action*"
          - "aquasecurity/*"
          - "anchore/*"
        update-types:
          - "security-update"
          - "patch"

  # ============================================
  # Terraform Dependencies (if using IaC)
  # ============================================
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
    commit-message:
      prefix: "feat(terraform)"
      prefix-development: "chore(terraform)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    ignore:
      # Ignore major provider updates that might break infrastructure
      - dependency-name: "hashicorp/aws"
        update-types: ["version-update:semver-major"]
      - dependency-name: "hashicorp/kubernetes"
        update-types: ["version-update:semver-major"]

  # ============================================
  # Kubernetes Manifests
  # ============================================
  - package-ecosystem: "kubernetes"
    directory: "/k8s"
    schedule:
      interval: "monthly"
      day: "second-monday"  
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@charlestakang"
    reviewers:
      - "@charlestakang"
    labels:
      - "dependencies"
      - "kubernetes"
      - "infrastructure"
    commit-message:
      prefix: "feat(k8s)"
      prefix-development: "chore(k8s)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"