# Codecov configuration for ResumeSync Pro
# https://docs.codecov.io/docs/codecov-yaml

# ============================================
# General Configuration
# ============================================
codecov:
  # Require the Codecov uploader to explicitly verify the CI provider
  require_ci_to_pass: true
  
  # Max report age in hours (24 hours)
  max_report_age: 24
  
  # Disable default notifications
  disable_default_path_fixes: false
  
  # Bot behavior
  bot: codecov-io
  
  # Strict YAML parsing
  strict_yaml_branch: main
  
  # Notify on error
  notify:
    after_n_builds: 3
    wait_for_ci: true

# ============================================
# Coverage Configuration
# ============================================
coverage:
  # Range for color coding (red -> yellow -> green)
  range: "70...90"
  
  # Round coverage to 2 decimal places
  precision: 2
  
  # Round coverage down, up, or nearest
  round: down
  
  # Status checks for pull requests
  status:
    # Project-level coverage requirements
    project:
      default:
        # Overall project coverage
        target: 80%
        threshold: 2%
        base: auto
        branches:
          - main
          - develop
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
      
      # API service coverage requirements
      api:
        target: 85%
        threshold: 1%
        paths:
          - "apps/api/**"
        flags:
          - api
        carryforward: true
        
      # Worker service coverage requirements  
      worker:
        target: 80%
        threshold: 2%
        paths:
          - "apps/worker/**"
        flags:
          - worker
        carryforward: true
        
      # Web application coverage requirements
      web:
        target: 75%
        threshold: 3%
        paths:
          - "apps/web/**"
        flags:
          - web
        carryforward: true
        
      # Unit tests specific coverage
      unit-tests:
        target: 90%
        threshold: 1%
        flags:
          - unit
        carryforward: false
        
      # Integration tests specific coverage
      integration-tests:
        target: 70%
        threshold: 5%
        flags:
          - integration
        carryforward: false
    
    # Patch-level coverage (changes in PR)
    patch:
      default:
        # Coverage for new/modified code
        target: 85%
        threshold: 0%
        base: auto
        if_not_found: success
        only_pulls: true
        
      # API patch coverage
      api:
        target: 90%
        paths:
          - "apps/api/**"
        flags:
          - api
          
      # Worker patch coverage
      worker:
        target: 85%
        paths:
          - "apps/worker/**"
        flags:
          - worker
          
      # Web patch coverage
      web:
        target: 80%
        paths:
          - "apps/web/**"
        flags:
          - web
    
    # Complexity checks
    changes:
      default:
        # Notify if complexity changes significantly
        branches:
          - main
          - develop

# ============================================
# Flags Configuration
# ============================================
flags:
  # API service flag
  api:
    paths:
      - apps/api/**/*.go
    carryforward: true
    carryforward_mode: labels
    
  # Worker service flag
  worker:
    paths:
      - apps/worker/**/*.go
    carryforward: true
    carryforward_mode: labels
    
  # Web application flag
  web:
    paths:
      - apps/web/**/*.ts
      - apps/web/**/*.tsx
      - apps/web/**/*.js
      - apps/web/**/*.jsx
    carryforward: true
    carryforward_mode: labels
    
  # Unit tests flag
  unit:
    paths:
      - "**/*_test.go"
      - "**/*.test.ts"
      - "**/*.test.tsx"
      - "**/*.test.js"
      - "**/*.test.jsx"
      - "**/*.spec.ts"
      - "**/*.spec.tsx"
      - "**/*.spec.js"
      - "**/*.spec.jsx"
    carryforward: false
    
  # Integration tests flag
  integration:
    paths:
      - "**/integration/**"
      - "**/e2e/**"
    carryforward: false

# ============================================
# File Ignores
# ============================================
ignore:
  # Generated files
  - "**/*.pb.go"
  - "**/*.gen.go"
  - "**/generated/**"
  - "**/gen/**"
  - "**/mock*.go"
  - "**/mocks/**"
  
  # Vendor directories
  - "**/vendor/**"
  - "**/node_modules/**"
  
  # Build and distribution
  - "**/build/**"
  - "**/dist/**"
  - "**/.next/**"
  - "**/out/**"
  
  # Test files (don't need coverage on test files themselves)
  - "**/*_test.go"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.spec.js"
  - "**/*.spec.jsx"
  
  # Configuration files
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/webpack.*.js"
  - "**/rollup.*.js"
  - "**/vite.*.js"
  - "**/next.config.js"
  - "**/jest.*.js"
  - "**/vitest.*.js"
  
  # Documentation and assets
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.svg"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/*.ico"
  
  # Scripts and tools
  - "**/scripts/**"
  - "**/tools/**"
  - "**/.github/**"
  
  # Database migrations
  - "**/migrations/**"
  - "**/seeds/**"
  
  # Kubernetes and Docker
  - "**/k8s/**"
  - "**/charts/**"
  - "**/Dockerfile*"
  - "**/docker-compose*.yml"

# ============================================
# Comment Configuration
# ============================================
comment:
  # Comment layout
  layout: "reach, diff, flags, files, footer"
  
  # Comment behavior
  behavior: default
  
  # Require code changes for comment
  require_changes: false
  
  # Require base report
  require_base: false
  
  # Require head report
  require_head: true
  
  # Show critical files with low coverage
  show_critical_paths: true
  
  # Show coverage for all changed files
  show_all_files: false
  
  # Annotations in PR diff view
  annotations: true

# ============================================
# GitHub Integration
# ============================================
github_checks:
  # Annotations on PR files
  annotations: true
  
  # Number of annotations per file
  annotations_limit: 10

# ============================================
# Component Configuration
# ============================================
component_management:
  # Define components for better organization
  default_rules:
    # Show all direct coverage changes
    statuses:
      - type: project
        target: auto
        threshold: 1%
    
    # Individual component tracking
    individual_components:
      - component_id: api
        name: "API Service"
        paths:
          - apps/api/**
      
      - component_id: worker
        name: "Worker Service"
        paths:
          - apps/worker/**
      
      - component_id: web
        name: "Web Application"
        paths:
          - apps/web/**
      
      - component_id: libs
        name: "Shared Libraries"
        paths:
          - libs/**
      
      - component_id: packages
        name: "Shared Packages"
        paths:
          - packages/**

# ============================================
# Parsers Configuration
# ============================================
parsers:
  # Go coverage parser settings
  go:
    partials_as_hits: false
  
  # JavaScript/TypeScript coverage parser settings
  javascript:
    enable_partials: false
  
  # V8 coverage format (Node.js)
  v8:
    enable_partials: false

# ============================================
# Upload Configuration
# ============================================
uploads:
  # Disable uploading for specific files
  disable_file_fixes: false
  
  # Network retry configuration
  network:
    max_retry: 3
    retry_delay: 5
    
  # Token configuration (set via environment variable)
  # token: ${CODECOV_TOKEN}

# ============================================
# Profiling Configuration
# ============================================
profiling:
  # Enable critical path analysis
  critical_files_paths:
    - apps/api/cmd/server/main.go
    - apps/api/internal/handlers/**
    - apps/worker/cmd/worker/main.go
    - apps/worker/internal/jobs/**
    - apps/web/src/pages/**
    - apps/web/src/components/**
    
  # Complexity thresholds
  complexity:
    # Flag files with complexity > 20
    threshold: 20

# ============================================
# Notifications Configuration
# ============================================
notify:
  # Manual trigger for notifications
  manual_trigger: false
  
  # Require all builds before notification
  wait_for_ci: true
  
  # Notify after N builds complete
  after_n_builds: 3
  
  # Slack notification (requires webhook setup)
  # slack:
  #   default:
  #     url: secret:SLACK_WEBHOOK_URL
  #     threshold: 1%
  #     branches:
  #       - main
  #     message: |
  #       Coverage {{changed}} for {{owner}}/{{repo}}
  #       {{#if decreased}}:warning:{{else}}:white_check_mark:{{/if}} {{compare}}%
  #     attachments: "sunburst, diff"
  
  # GitHub Status (enabled by default)
  # github_status:
  #   default:
  #     branches:
  #       - main
  #       - develop