version: '3.8'

services:
  postgres:
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: resumesync
        POSTGRES_PASSWORD: resumesync123
        POSTGRES_DB: resumesync_dev
      volumes:
        - postgres_dev_data:/var/lib/postgresql/data
        - ./docker/postgres:/docker-entrypoint-initdb.d
      command: postgres -c log_statement=all -c log_destination=stderr

  redis:
      ports:
        - "6379:6379"
      volumes:
        - redis_dev_data:/data
      command: redis-server --appendonly yes --loglevel verbose

  minio:
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin123
        MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      volumes:
        - minio_dev_data:/data
        - ./docker/minio:/docker-entrypoint-initdb.d

  api:
      build:
        context: ./apps/api
        dockerfile: Dockerfile.dev
        target: development
      ports:
        - "8080:8080"
        - "2345:2345"
      environment:
        GIN_MODE: debug
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USER: resumesync
        DB_PASSWORD: resumesync123
        DB_NAME: resumesync_dev
        REDIS_HOST: redis
        REDIS_PORT: 6379
        MINIO_ENDPOINT: minio:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin123
        MINIO_USE_SSL: "false"
        JWT_SECRET: dev-secret-key-not-for-production
        LOG_LEVEL: debug
        HOT_RELOAD: "true"
      volumes:
        - ./apps/api:/app
        - ./libs:/libs
        - go_dev_modules:/go/pkg/mod
        - ./apps/api/tmp:/tmp
      working_dir: /app
      # Temporarily using go run until Air is fixed
      command: go run cmd/server/main.go
      stdin_open: true
      tty: true

  worker:
      build:
        context: ./apps/worker
        dockerfile: Dockerfile.dev
        target: development
      environment:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USER: resumesync
        DB_PASSWORD: resumesync123
        DB_NAME: resumesync_dev
        REDIS_HOST: redis
        REDIS_PORT: 6379
        MINIO_ENDPOINT: minio:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin123
        MINIO_USE_SSL: "false"
        LOG_LEVEL: debug
        HOT_RELOAD: "true"
        WORKER_CONCURRENCY: 1
      volumes:
        - ./apps/worker:/app
        - ./libs:/libs
        - go_dev_modules:/go/pkg/mod
        - ./apps/worker/tmp:/tmp
      working_dir: /app
      # Temporarily using go run until Air is fixed
      command: go run cmd/server/main.go
      stdin_open: true
      tty: true

  web:
      build:
        context: ./apps/web
        dockerfile: Dockerfile.dev
        target: development
      ports:
        - "3000:3000"
      environment:
        NODE_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8080
        NEXT_PUBLIC_APP_URL: http://localhost:3000
        DATABASE_URL: postgresql://resumesync:resumesync123@postgres:5432/resumesync_dev
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: dev-nextauth-secret-not-for-production
        WATCHPACK_POLLING: "true"
        CHOKIDAR_USEPOLLING: "true"
      volumes:
        - ./apps/web:/app
        - ./packages:/packages
        - web_node_modules:/app/node_modules
        - web_next_cache:/app/.next
        - /app/node_modules/.cache
      working_dir: /app
      command: npm run dev
      stdin_open: true
      tty: true

volumes:
  postgres_dev_data:
  redis_dev_data:
  minio_dev_data:
  go_dev_modules:
  web_node_modules:
  web_next_cache:
